# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'chupWBgoRR.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1922, 1080)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1920, 1080))
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tab_nhap_thong_tin = QWidget()
        self.tab_nhap_thong_tin.setObjectName(u"tab_nhap_thong_tin")
        self.groupBox = QGroupBox(self.tab_nhap_thong_tin)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(100, 170, 800, 500))
        self.groupBox.setToolTipDuration(-1)
        self.groupBox.setFlat(False)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 50, 180, 240))
        self.label_5.setPixmap(QPixmap(u"../images/bk1.png"))
        self.label_5.setScaledContents(True)
        self.chonAnhBT = QPushButton(self.groupBox)
        self.chonAnhBT.setObjectName(u"chonAnhBT")
        self.chonAnhBT.setGeometry(QRect(80, 320, 91, 31))
        self.textEdit_2 = QTextEdit(self.groupBox)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(338, 117, 422, 37))
        font = QFont()
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_16 = QTextEdit(self.groupBox)
        self.textEdit_16.setObjectName(u"textEdit_16")
        self.textEdit_16.setGeometry(QRect(338, 51, 422, 37))
        self.textEdit_16.setFont(font)
        self.textEdit_3 = QTextEdit(self.groupBox)
        self.textEdit_3.setObjectName(u"textEdit_3")
        self.textEdit_3.setGeometry(QRect(338, 183, 422, 37))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.textEdit_3.sizePolicy().hasHeightForWidth())
        self.textEdit_3.setSizePolicy(sizePolicy1)
        self.textEdit_3.setFont(font)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(271, 117, 60, 16))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(271, 51, 27, 16))
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(271, 183, 44, 16))
        self.groupBox_2 = QGroupBox(self.tab_nhap_thong_tin)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(1020, 170, 800, 500))
        self.groupBox_2.setToolTipDuration(-1)
        self.groupBox_2.setFlat(False)
        self.Tab_diem_va_kq = QTabWidget(self.groupBox_2)
        self.Tab_diem_va_kq.setObjectName(u"Tab_diem_va_kq")
        self.Tab_diem_va_kq.setGeometry(QRect(10, 30, 780, 460))
        self.tab_diem = QWidget()
        self.tab_diem.setObjectName(u"tab_diem")
        self.tableWidget = QTableWidget(self.tab_diem)
        if (self.tableWidget.columnCount() < 15):
            self.tableWidget.setColumnCount(15)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, __qtablewidgetitem14)
        if (self.tableWidget.rowCount() < 10):
            self.tableWidget.setRowCount(10)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, __qtablewidgetitem20)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, __qtablewidgetitem23)
        __qtablewidgetitem24 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, __qtablewidgetitem24)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 10, 750, 420))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.Tab_diem_va_kq.addTab(self.tab_diem, "")
        self.tab_kq = QWidget()
        self.tab_kq.setObjectName(u"tab_kq")
        self.tableWidget_3 = QTableWidget(self.tab_kq)
        if (self.tableWidget_3.columnCount() < 12):
            self.tableWidget_3.setColumnCount(12)
        __qtablewidgetitem25 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, __qtablewidgetitem25)
        __qtablewidgetitem26 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, __qtablewidgetitem26)
        __qtablewidgetitem27 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, __qtablewidgetitem27)
        __qtablewidgetitem28 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, __qtablewidgetitem28)
        __qtablewidgetitem29 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, __qtablewidgetitem29)
        __qtablewidgetitem30 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, __qtablewidgetitem30)
        __qtablewidgetitem31 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, __qtablewidgetitem31)
        __qtablewidgetitem32 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, __qtablewidgetitem32)
        __qtablewidgetitem33 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, __qtablewidgetitem33)
        __qtablewidgetitem34 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, __qtablewidgetitem34)
        __qtablewidgetitem35 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, __qtablewidgetitem35)
        __qtablewidgetitem36 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, __qtablewidgetitem36)
        if (self.tableWidget_3.rowCount() < 10):
            self.tableWidget_3.setRowCount(10)
        __qtablewidgetitem37 = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, __qtablewidgetitem37)
        __qtablewidgetitem38 = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, __qtablewidgetitem38)
        __qtablewidgetitem39 = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, __qtablewidgetitem39)
        __qtablewidgetitem40 = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, __qtablewidgetitem40)
        __qtablewidgetitem41 = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, __qtablewidgetitem41)
        __qtablewidgetitem42 = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, __qtablewidgetitem42)
        __qtablewidgetitem43 = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(6, __qtablewidgetitem43)
        __qtablewidgetitem44 = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(7, __qtablewidgetitem44)
        __qtablewidgetitem45 = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(8, __qtablewidgetitem45)
        __qtablewidgetitem46 = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(9, __qtablewidgetitem46)
        self.tableWidget_3.setObjectName(u"tableWidget_3")
        self.tableWidget_3.setGeometry(QRect(10, 10, 750, 420))
        self.tableWidget_3.setAutoFillBackground(False)
        self.tableWidget_3.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.Tab_diem_va_kq.addTab(self.tab_kq, "")
        self.XemKQBT = QPushButton(self.tab_nhap_thong_tin)
        self.XemKQBT.setObjectName(u"XemKQBT")
        self.XemKQBT.setGeometry(QRect(1500, 920, 120, 30))
        self.pushButton_7 = QPushButton(self.tab_nhap_thong_tin)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(1650, 920, 120, 30))
        self.tabTruocBT_2 = QPushButton(self.tab_nhap_thong_tin)
        self.tabTruocBT_2.setObjectName(u"tabTruocBT_2")
        self.tabTruocBT_2.setGeometry(QRect(150, 920, 120, 30))
        self.tabSauBT_2 = QPushButton(self.tab_nhap_thong_tin)
        self.tabSauBT_2.setObjectName(u"tabSauBT_2")
        self.tabSauBT_2.setGeometry(QRect(300, 920, 120, 30))
        self.label = QLabel(self.tab_nhap_thong_tin)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(768, 51, 362, 48))
        font1 = QFont()
        font1.setPointSize(24)
        font1.setBold(True)
        font1.setWeight(75)
        self.label.setFont(font1)
        self.xoaBT = QPushButton(self.tab_nhap_thong_tin)
        self.xoaBT.setObjectName(u"xoaBT")
        self.xoaBT.setGeometry(QRect(1350, 920, 120, 30))
        self.tabWidget.addTab(self.tab_nhap_thong_tin, "")
        self.label.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.XemKQBT.raise_()
        self.pushButton_7.raise_()
        self.tabTruocBT_2.raise_()
        self.tabSauBT_2.raise_()
        self.xoaBT.raise_()
        self.tab_chup_anh = QWidget()
        self.tab_chup_anh.setObjectName(u"tab_chup_anh")
        self.groupBox_3 = QGroupBox(self.tab_chup_anh)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(20, 310, 411, 111))
        self.layoutWidget = QWidget(self.groupBox_3)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 60, 381, 31))
        self.horizontalLayout_6 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.nguongSlider = QSlider(self.layoutWidget)
        self.nguongSlider.setObjectName(u"nguongSlider")
        self.nguongSlider.setMinimum(0)
        self.nguongSlider.setMaximum(255)
        self.nguongSlider.setValue(65)
        self.nguongSlider.setSliderPosition(65)
        self.nguongSlider.setOrientation(Qt.Horizontal)

        self.horizontalLayout_6.addWidget(self.nguongSlider)

        self.nguongDSB = QDoubleSpinBox(self.layoutWidget)
        self.nguongDSB.setObjectName(u"nguongDSB")
        self.nguongDSB.setDecimals(0)
        self.nguongDSB.setMinimum(0.000000000000000)
        self.nguongDSB.setMaximum(254.000000000000000)
        self.nguongDSB.setValue(65.000000000000000)

        self.horizontalLayout_6.addWidget(self.nguongDSB)

        self.doSangLB_3 = QLabel(self.groupBox_3)
        self.doSangLB_3.setObjectName(u"doSangLB_3")
        self.doSangLB_3.setGeometry(QRect(10, 30, 377, 16))
        self.doSangLB_3.setAlignment(Qt.AlignCenter)
        self.cameraOptionGB = QGroupBox(self.tab_chup_anh)
        self.cameraOptionGB.setObjectName(u"cameraOptionGB")
        self.cameraOptionGB.setGeometry(QRect(20, 30, 411, 261))
        self.verticalLayoutWidget_3 = QWidget(self.cameraOptionGB)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(10, 50, 381, 191))
        self.verticalLayout_6 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.chonCameraLB = QLabel(self.verticalLayoutWidget_3)
        self.chonCameraLB.setObjectName(u"chonCameraLB")

        self.gridLayout.addWidget(self.chonCameraLB, 0, 0, 1, 1)

        self.chonCamCB = QComboBox(self.verticalLayoutWidget_3)
        self.chonCamCB.addItem("")
        self.chonCamCB.addItem("")
        self.chonCamCB.addItem("")
        self.chonCamCB.setObjectName(u"chonCamCB")

        self.gridLayout.addWidget(self.chonCamCB, 0, 1, 1, 1)

        self.chonKenhLB = QLabel(self.verticalLayoutWidget_3)
        self.chonKenhLB.setObjectName(u"chonKenhLB")

        self.gridLayout.addWidget(self.chonKenhLB, 1, 0, 1, 1)

        self.chonKenhCB = QComboBox(self.verticalLayoutWidget_3)
        self.chonKenhCB.addItem("")
        self.chonKenhCB.addItem("")
        self.chonKenhCB.setObjectName(u"chonKenhCB")

        self.gridLayout.addWidget(self.chonKenhCB, 1, 1, 1, 1)


        self.horizontalLayout_8.addLayout(self.gridLayout)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_8.addItem(self.horizontalSpacer_3)

        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.smallScreenRB = QRadioButton(self.verticalLayoutWidget_3)
        self.smallScreenRB.setObjectName(u"smallScreenRB")
        self.smallScreenRB.setChecked(True)

        self.gridLayout_2.addWidget(self.smallScreenRB, 1, 0, 1, 1)

        self.orginalScreenRB = QRadioButton(self.verticalLayoutWidget_3)
        self.orginalScreenRB.setObjectName(u"orginalScreenRB")

        self.gridLayout_2.addWidget(self.orginalScreenRB, 2, 0, 1, 1)


        self.horizontalLayout_8.addLayout(self.gridLayout_2)


        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)


        self.verticalLayout_6.addLayout(self.horizontalLayout_9)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.doSangLB = QLabel(self.verticalLayoutWidget_3)
        self.doSangLB.setObjectName(u"doSangLB")
        self.doSangLB.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.doSangLB)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.BrightnessSlider = QSlider(self.verticalLayoutWidget_3)
        self.BrightnessSlider.setObjectName(u"BrightnessSlider")
        self.BrightnessSlider.setMinimum(-50)
        self.BrightnessSlider.setMaximum(50)
        self.BrightnessSlider.setSliderPosition(0)
        self.BrightnessSlider.setOrientation(Qt.Horizontal)

        self.horizontalLayout.addWidget(self.BrightnessSlider)

        self.doSangDSB = QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.doSangDSB.setObjectName(u"doSangDSB")
        self.doSangDSB.setDecimals(0)
        self.doSangDSB.setMinimum(-50.000000000000000)
        self.doSangDSB.setMaximum(50.000000000000000)
        self.doSangDSB.setValue(0.000000000000000)

        self.horizontalLayout.addWidget(self.doSangDSB)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.doSangLB_2 = QLabel(self.verticalLayoutWidget_3)
        self.doSangLB_2.setObjectName(u"doSangLB_2")
        self.doSangLB_2.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.doSangLB_2)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.ContrastSlider = QSlider(self.verticalLayoutWidget_3)
        self.ContrastSlider.setObjectName(u"ContrastSlider")
        self.ContrastSlider.setMinimum(-50)
        self.ContrastSlider.setMaximum(50)
        self.ContrastSlider.setSliderPosition(0)
        self.ContrastSlider.setOrientation(Qt.Horizontal)

        self.horizontalLayout_4.addWidget(self.ContrastSlider)

        self.doTuongPhanDSB = QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.doTuongPhanDSB.setObjectName(u"doTuongPhanDSB")
        self.doTuongPhanDSB.setDecimals(0)
        self.doTuongPhanDSB.setMinimum(-50.000000000000000)
        self.doTuongPhanDSB.setMaximum(50.000000000000000)
        self.doTuongPhanDSB.setValue(0.000000000000000)

        self.horizontalLayout_4.addWidget(self.doTuongPhanDSB)


        self.verticalLayout.addLayout(self.horizontalLayout_4)


        self.verticalLayout_6.addLayout(self.verticalLayout)

        self.groupBox_4 = QGroupBox(self.tab_chup_anh)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(20, 450, 411, 121))
        self.layoutWidget_2 = QWidget(self.groupBox_4)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(30, 40, 341, 61))
        self.gridLayout_3 = QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.hienduongbaoQRB = QRadioButton(self.layoutWidget_2)
        self.hienduongbaoQRB.setObjectName(u"hienduongbaoQRB")

        self.gridLayout_3.addWidget(self.hienduongbaoQRB, 2, 0, 1, 1)

        self.tatduongbaoQRB = QRadioButton(self.layoutWidget_2)
        self.tatduongbaoQRB.setObjectName(u"tatduongbaoQRB")
        self.tatduongbaoQRB.setChecked(True)

        self.gridLayout_3.addWidget(self.tatduongbaoQRB, 1, 0, 1, 1)

        self.groupBox_5 = QGroupBox(self.tab_chup_anh)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(20, 600, 411, 121))
        self.layoutWidget_5 = QWidget(self.groupBox_5)
        self.layoutWidget_5.setObjectName(u"layoutWidget_5")
        self.layoutWidget_5.setGeometry(QRect(30, 30, 341, 31))
        self.horizontalLayout_10 = QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.chonCameraLB_2 = QLabel(self.layoutWidget_5)
        self.chonCameraLB_2.setObjectName(u"chonCameraLB_2")

        self.horizontalLayout_10.addWidget(self.chonCameraLB_2)

        self.choManHinhCB = QComboBox(self.layoutWidget_5)
        self.choManHinhCB.addItem("")
        self.choManHinhCB.addItem("")
        self.choManHinhCB.addItem("")
        self.choManHinhCB.addItem("")
        self.choManHinhCB.addItem("")
        self.choManHinhCB.addItem("")
        self.choManHinhCB.setObjectName(u"choManHinhCB")

        self.horizontalLayout_10.addWidget(self.choManHinhCB)

        self.layoutWidget_9 = QWidget(self.groupBox_5)
        self.layoutWidget_9.setObjectName(u"layoutWidget_9")
        self.layoutWidget_9.setGeometry(QRect(30, 70, 341, 31))
        self.horizontalLayout_11 = QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.chonCameraLB_3 = QLabel(self.layoutWidget_9)
        self.chonCameraLB_3.setObjectName(u"chonCameraLB_3")

        self.horizontalLayout_11.addWidget(self.chonCameraLB_3)

        self.chonDieuHuongCB = QComboBox(self.layoutWidget_9)
        self.chonDieuHuongCB.addItem("")
        self.chonDieuHuongCB.addItem("")
        self.chonDieuHuongCB.addItem("")
        self.chonDieuHuongCB.addItem("")
        self.chonDieuHuongCB.addItem("")
        self.chonDieuHuongCB.setObjectName(u"chonDieuHuongCB")

        self.horizontalLayout_11.addWidget(self.chonDieuHuongCB)

        self.xemKetQuaBT = QPushButton(self.tab_chup_anh)
        self.xemKetQuaBT.setObjectName(u"xemKetQuaBT")
        self.xemKetQuaBT.setGeometry(QRect(1500, 920, 120, 30))
        self.tabSauBT = QPushButton(self.tab_chup_anh)
        self.tabSauBT.setObjectName(u"tabSauBT")
        self.tabSauBT.setGeometry(QRect(300, 920, 120, 30))
        self.chupBT = QPushButton(self.tab_chup_anh)
        self.chupBT.setObjectName(u"chupBT")
        self.chupBT.setGeometry(QRect(1650, 920, 120, 30))
        self.tabTruocBT = QPushButton(self.tab_chup_anh)
        self.tabTruocBT.setObjectName(u"tabTruocBT")
        self.tabTruocBT.setGeometry(QRect(150, 920, 120, 30))
        self.groupBox_6 = QGroupBox(self.tab_chup_anh)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(449, 30, 1381, 840))
        self.anhMauLB = QLabel(self.groupBox_6)
        self.anhMauLB.setObjectName(u"anhMauLB")
        self.anhMauLB.setGeometry(QRect(1120, 30, 240, 320))
        self.anhMauLB.setPixmap(QPixmap(u"../images/bantayngua.png"))
        self.anhMauLB.setScaledContents(True)
        self.label_3 = QLabel(self.groupBox_6)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(1210, 360, 55, 16))
        self.cameraLB = QLabel(self.groupBox_6)
        self.cameraLB.setObjectName(u"cameraLB")
        self.cameraLB.setGeometry(QRect(20, 30, 1080, 720))
        self.cameraLB.setPixmap(QPixmap(u"../images/mau_ngua_ban_tay.png"))
        self.cameraLB.setScaledContents(False)
        self.cameraLB.setAlignment(Qt.AlignCenter)
        self.noteLB = QLabel(self.groupBox_6)
        self.noteLB.setObjectName(u"noteLB")
        self.noteLB.setGeometry(QRect(20, 760, 1340, 61))
        self.groupBox_7 = QGroupBox(self.tab_chup_anh)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(20, 750, 411, 121))
        self.layoutWidget_8 = QWidget(self.groupBox_7)
        self.layoutWidget_8.setObjectName(u"layoutWidget_8")
        self.layoutWidget_8.setGeometry(QRect(30, 40, 341, 61))
        self.gridLayout_9 = QGridLayout(self.layoutWidget_8)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.tuDongQRB = QRadioButton(self.layoutWidget_8)
        self.tuDongQRB.setObjectName(u"tuDongQRB")
        self.tuDongQRB.setChecked(True)

        self.gridLayout_9.addWidget(self.tuDongQRB, 1, 0, 1, 1)

        self.thuCongQRB = QRadioButton(self.layoutWidget_8)
        self.thuCongQRB.setObjectName(u"thuCongQRB")

        self.gridLayout_9.addWidget(self.thuCongQRB, 2, 0, 1, 1)

        self.luiBT = QPushButton(self.tab_chup_anh)
        self.luiBT.setObjectName(u"luiBT")
        self.luiBT.setGeometry(QRect(1050, 920, 120, 30))
        self.tienBT = QPushButton(self.tab_chup_anh)
        self.tienBT.setObjectName(u"tienBT")
        self.tienBT.setGeometry(QRect(1200, 920, 120, 30))
        self.resetBT = QPushButton(self.tab_chup_anh)
        self.resetBT.setObjectName(u"resetBT")
        self.resetBT.setGeometry(QRect(1350, 920, 120, 30))
        self.tabWidget.addTab(self.tab_chup_anh, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1922, 26))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuCalibration = QMenu(self.menubar)
        self.menuCalibration.setObjectName(u"menuCalibration")
        self.menuQuit = QMenu(self.menubar)
        self.menuQuit.setObjectName(u"menuQuit")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCalibration.menuAction())
        self.menubar.addAction(self.menuQuit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.Tab_diem_va_kq.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Th\u00f4ng tin", None))
        self.label_5.setText("")
        self.chonAnhBT.setText(QCoreApplication.translate("MainWindow", u"Ch\u1ecdn \u1ea3nh", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Ng\u00e0y sinh:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"T\u00ean:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u0110\u1ecba ch\u1ec9:", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"K\u1ebft qu\u1ea3", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"K\u00edch th\u01b0\u1edbc \u1ea3nh", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"T\u00ean \u0111i\u1ec3m", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"V\u1ecb tr\u00ed", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"K\u00edch th\u01b0\u1edbc \u1ea3nh", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"T\u00ean \u0111i\u1ec3m", None));
        ___qtablewidgetitem5 = self.tableWidget.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"V\u1ecb tr\u00ed", None));
        ___qtablewidgetitem6 = self.tableWidget.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"K\u00edch th\u01b0\u1edbc \u1ea3nh", None));
        ___qtablewidgetitem7 = self.tableWidget.horizontalHeaderItem(7)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"T\u00ean \u0111i\u1ec3m", None));
        ___qtablewidgetitem8 = self.tableWidget.horizontalHeaderItem(8)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem9 = self.tableWidget.horizontalHeaderItem(9)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"V\u1ecb tr\u00ed", None));
        ___qtablewidgetitem10 = self.tableWidget.horizontalHeaderItem(10)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"T\u00ean \u0111i\u1ec3m", None));
        ___qtablewidgetitem11 = self.tableWidget.horizontalHeaderItem(11)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"V\u1ecb tr\u00ed", None));
        ___qtablewidgetitem12 = self.tableWidget.horizontalHeaderItem(12)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"K\u00edch th\u01b0\u1edbc \u1ea3nh", None));
        ___qtablewidgetitem13 = self.tableWidget.horizontalHeaderItem(13)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"T\u00ean \u0111i\u1ec3m", None));
        ___qtablewidgetitem14 = self.tableWidget.horizontalHeaderItem(14)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"V\u1ecb tr\u00ed", None));
        ___qtablewidgetitem15 = self.tableWidget.verticalHeaderItem(0)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"1", None));
        ___qtablewidgetitem16 = self.tableWidget.verticalHeaderItem(1)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"2", None));
        ___qtablewidgetitem17 = self.tableWidget.verticalHeaderItem(2)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"3", None));
        ___qtablewidgetitem18 = self.tableWidget.verticalHeaderItem(3)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"4", None));
        ___qtablewidgetitem19 = self.tableWidget.verticalHeaderItem(4)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("MainWindow", u"5", None));
        ___qtablewidgetitem20 = self.tableWidget.verticalHeaderItem(5)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("MainWindow", u"6", None));
        ___qtablewidgetitem21 = self.tableWidget.verticalHeaderItem(6)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("MainWindow", u"7", None));
        ___qtablewidgetitem22 = self.tableWidget.verticalHeaderItem(7)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("MainWindow", u"8", None));
        ___qtablewidgetitem23 = self.tableWidget.verticalHeaderItem(8)
        ___qtablewidgetitem23.setText(QCoreApplication.translate("MainWindow", u"9", None));
        ___qtablewidgetitem24 = self.tableWidget.verticalHeaderItem(9)
        ___qtablewidgetitem24.setText(QCoreApplication.translate("MainWindow", u"10", None));
        self.Tab_diem_va_kq.setTabText(self.Tab_diem_va_kq.indexOf(self.tab_diem), QCoreApplication.translate("MainWindow", u"V\u1ecb tr\u00ed c\u00e1c \u0111i\u1ec3m", None))
        ___qtablewidgetitem25 = self.tableWidget_3.horizontalHeaderItem(0)
        ___qtablewidgetitem25.setText(QCoreApplication.translate("MainWindow", u"K\u00edch th\u01b0\u1edbc \u1ea3nh", None));
        ___qtablewidgetitem26 = self.tableWidget_3.horizontalHeaderItem(1)
        ___qtablewidgetitem26.setText(QCoreApplication.translate("MainWindow", u"T\u00ean", None));
        ___qtablewidgetitem27 = self.tableWidget_3.horizontalHeaderItem(2)
        ___qtablewidgetitem27.setText(QCoreApplication.translate("MainWindow", u"Kho\u1ea3ng c\u00e1ch", None));
        ___qtablewidgetitem28 = self.tableWidget_3.horizontalHeaderItem(3)
        ___qtablewidgetitem28.setText(QCoreApplication.translate("MainWindow", u"K\u00edch th\u01b0\u1edbc \u1ea3nh", None));
        ___qtablewidgetitem29 = self.tableWidget_3.horizontalHeaderItem(4)
        ___qtablewidgetitem29.setText(QCoreApplication.translate("MainWindow", u"T\u00ean", None));
        ___qtablewidgetitem30 = self.tableWidget_3.horizontalHeaderItem(5)
        ___qtablewidgetitem30.setText(QCoreApplication.translate("MainWindow", u"Kho\u1ea3ng c\u00e1ch", None));
        ___qtablewidgetitem31 = self.tableWidget_3.horizontalHeaderItem(6)
        ___qtablewidgetitem31.setText(QCoreApplication.translate("MainWindow", u"K\u00edch th\u01b0\u1edbc \u1ea3nh", None));
        ___qtablewidgetitem32 = self.tableWidget_3.horizontalHeaderItem(7)
        ___qtablewidgetitem32.setText(QCoreApplication.translate("MainWindow", u"T\u00ean", None));
        ___qtablewidgetitem33 = self.tableWidget_3.horizontalHeaderItem(8)
        ___qtablewidgetitem33.setText(QCoreApplication.translate("MainWindow", u"Kho\u1ea3ng c\u00e1ch", None));
        ___qtablewidgetitem34 = self.tableWidget_3.horizontalHeaderItem(9)
        ___qtablewidgetitem34.setText(QCoreApplication.translate("MainWindow", u"K\u00edch th\u01b0\u1edbc \u1ea3nh", None));
        ___qtablewidgetitem35 = self.tableWidget_3.horizontalHeaderItem(10)
        ___qtablewidgetitem35.setText(QCoreApplication.translate("MainWindow", u"T\u00ean", None));
        ___qtablewidgetitem36 = self.tableWidget_3.horizontalHeaderItem(11)
        ___qtablewidgetitem36.setText(QCoreApplication.translate("MainWindow", u"Kho\u1ea3ng c\u00e1ch", None));
        ___qtablewidgetitem37 = self.tableWidget_3.verticalHeaderItem(0)
        ___qtablewidgetitem37.setText(QCoreApplication.translate("MainWindow", u"1", None));
        ___qtablewidgetitem38 = self.tableWidget_3.verticalHeaderItem(1)
        ___qtablewidgetitem38.setText(QCoreApplication.translate("MainWindow", u"2", None));
        ___qtablewidgetitem39 = self.tableWidget_3.verticalHeaderItem(2)
        ___qtablewidgetitem39.setText(QCoreApplication.translate("MainWindow", u"3", None));
        ___qtablewidgetitem40 = self.tableWidget_3.verticalHeaderItem(3)
        ___qtablewidgetitem40.setText(QCoreApplication.translate("MainWindow", u"4", None));
        ___qtablewidgetitem41 = self.tableWidget_3.verticalHeaderItem(4)
        ___qtablewidgetitem41.setText(QCoreApplication.translate("MainWindow", u"5", None));
        ___qtablewidgetitem42 = self.tableWidget_3.verticalHeaderItem(5)
        ___qtablewidgetitem42.setText(QCoreApplication.translate("MainWindow", u"6", None));
        ___qtablewidgetitem43 = self.tableWidget_3.verticalHeaderItem(6)
        ___qtablewidgetitem43.setText(QCoreApplication.translate("MainWindow", u"7", None));
        ___qtablewidgetitem44 = self.tableWidget_3.verticalHeaderItem(7)
        ___qtablewidgetitem44.setText(QCoreApplication.translate("MainWindow", u"8", None));
        ___qtablewidgetitem45 = self.tableWidget_3.verticalHeaderItem(8)
        ___qtablewidgetitem45.setText(QCoreApplication.translate("MainWindow", u"9", None));
        ___qtablewidgetitem46 = self.tableWidget_3.verticalHeaderItem(9)
        ___qtablewidgetitem46.setText(QCoreApplication.translate("MainWindow", u"10", None));
        self.Tab_diem_va_kq.setTabText(self.Tab_diem_va_kq.indexOf(self.tab_kq), QCoreApplication.translate("MainWindow", u"Kho\u1ea3ng c\u00e1ch", None))
        self.XemKQBT.setText(QCoreApplication.translate("MainWindow", u"Xem KQ", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"L\u01b0u ", None))
        self.tabTruocBT_2.setText(QCoreApplication.translate("MainWindow", u"Tab tr\u01b0\u1edbc", None))
        self.tabSauBT_2.setText(QCoreApplication.translate("MainWindow", u"Tab sau", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"NH\u1eacP TH\u00d4NG TIN", None))
        self.xoaBT.setText(QCoreApplication.translate("MainWindow", u"Xo\u00e1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_nhap_thong_tin), QCoreApplication.translate("MainWindow", u"Nh\u1eadp th\u00f4ng tin", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\u0110i\u1ec1u ch\u1ec9nh ng\u01b0\u1ee1ng", None))
        self.doSangLB_3.setText(QCoreApplication.translate("MainWindow", u"Ng\u01b0\u1ee1ng t\u00e1ch n\u1ec1n", None))
        self.cameraOptionGB.setTitle(QCoreApplication.translate("MainWindow", u"Ch\u1ecdn Camera", None))
        self.chonCameraLB.setText(QCoreApplication.translate("MainWindow", u"Ch\u1ecdn camera:", None))
        self.chonCamCB.setItemText(0, QCoreApplication.translate("MainWindow", u"T\u1eaft", None))
        self.chonCamCB.setItemText(1, QCoreApplication.translate("MainWindow", u"Camera 0", None))
        self.chonCamCB.setItemText(2, QCoreApplication.translate("MainWindow", u"Camera 1", None))

        self.chonKenhLB.setText(QCoreApplication.translate("MainWindow", u"Ch\u1ecdn k\u00eanh:", None))
        self.chonKenhCB.setItemText(0, QCoreApplication.translate("MainWindow", u"RGB", None))
        self.chonKenhCB.setItemText(1, QCoreApplication.translate("MainWindow", u"Grayscale", None))

        self.smallScreenRB.setText(QCoreApplication.translate("MainWindow", u"M\u00e0n h\u00ecnh nh\u1ecf", None))
        self.orginalScreenRB.setText(QCoreApplication.translate("MainWindow", u"M\u00e0n h\u00ecnh g\u1ed1c", None))
        self.doSangLB.setText(QCoreApplication.translate("MainWindow", u"\u0110\u1ed9 s\u00e1ng", None))
        self.doSangLB_2.setText(QCoreApplication.translate("MainWindow", u"\u0110\u1ed9 t\u01b0\u01a1ng ph\u1ea3n", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Tu\u1ef3 ch\u1ecdn", None))
        self.hienduongbaoQRB.setText(QCoreApplication.translate("MainWindow", u"Hi\u1ec7n \u0111\u01b0\u1eddng bao", None))
        self.tatduongbaoQRB.setText(QCoreApplication.translate("MainWindow", u"T\u1eaft \u0111\u01b0\u1eddng bao", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Ch\u1ecdn m\u00e0n h\u00ecnh", None))
        self.chonCameraLB_2.setText(QCoreApplication.translate("MainWindow", u"Ch\u1ecdn m\u00e0n h\u00ecnh", None))
        self.choManHinhCB.setItemText(0, QCoreApplication.translate("MainWindow", u"T\u1ef1 \u0111\u1ed9ng", None))
        self.choManHinhCB.setItemText(1, QCoreApplication.translate("MainWindow", u"2:3 (1080 x 720) ", None))
        self.choManHinhCB.setItemText(2, QCoreApplication.translate("MainWindow", u"16:9 (960 x 540) ", None))
        self.choManHinhCB.setItemText(3, QCoreApplication.translate("MainWindow", u"16:9 (640 x 360) ", None))
        self.choManHinhCB.setItemText(4, QCoreApplication.translate("MainWindow", u"4:3 (960 x 720) ", None))
        self.choManHinhCB.setItemText(5, QCoreApplication.translate("MainWindow", u"4:3 (640 x 480) ", None))

        self.chonCameraLB_3.setText(QCoreApplication.translate("MainWindow", u"\u0110i\u1ec1u ch\u1ec9nh h\u01b0\u1edbng", None))
        self.chonDieuHuongCB.setItemText(0, QCoreApplication.translate("MainWindow", u"Kh\u00f4ng", None))
        self.chonDieuHuongCB.setItemText(1, QCoreApplication.translate("MainWindow", u"L\u1eadt", None))
        self.chonDieuHuongCB.setItemText(2, QCoreApplication.translate("MainWindow", u"\u0110\u1ea3o ng\u01b0\u1ee3c", None))
        self.chonDieuHuongCB.setItemText(3, QCoreApplication.translate("MainWindow", u"Xoay 90 \u0111\u1ed9 sang tr\u00e1i", None))
        self.chonDieuHuongCB.setItemText(4, QCoreApplication.translate("MainWindow", u"Xoay 90 \u0111\u1ed9 sang ph\u1ea3i", None))

        self.xemKetQuaBT.setText(QCoreApplication.translate("MainWindow", u"Xem \u1ea3nh k\u1ebft qu\u1ea3", None))
        self.tabSauBT.setText(QCoreApplication.translate("MainWindow", u"Tab sau", None))
        self.chupBT.setText(QCoreApplication.translate("MainWindow", u"Ch\u1ee5p", None))
        self.tabTruocBT.setText(QCoreApplication.translate("MainWindow", u"Tab tr\u01b0\u1edbc", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.anhMauLB.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u1ea2nh m\u1eabu", None))
        self.cameraLB.setText("")
        self.noteLB.setText("")
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Ch\u1ecdn ch\u1ebf \u0111\u1ed9 ch\u1ee5p", None))
        self.tuDongQRB.setText(QCoreApplication.translate("MainWindow", u"T\u1ef1 \u0111\u1ed9ng", None))
        self.thuCongQRB.setText(QCoreApplication.translate("MainWindow", u"Th\u1ee7 c\u00f4ng", None))
        self.luiBT.setText(QCoreApplication.translate("MainWindow", u"L\u00f9i", None))
        self.tienBT.setText(QCoreApplication.translate("MainWindow", u"Ti\u1ebfn", None))
        self.resetBT.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_chup_anh), QCoreApplication.translate("MainWindow", u"Ch\u1ee5p \u1ea3nh", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuCalibration.setTitle(QCoreApplication.translate("MainWindow", u"Calibration", None))
        self.menuQuit.setTitle(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

